import express from "express";
const router = express.Router();
import authRouter from "../modules/auth/auth.route.js";
import serviceProviderRouter from "../modules/serviceProvider/serviceProvider.route.js";
import caregiverRouter from "../modules/careGiver/careGiver.route.js";
import cpPatientRouter from "../modules/cpPatient/cpPatient.routes.js";
import assessmentRouter from "../modules/assessment/assessment.route.js";
import userRouter from "../modules/user/user.route.js";
import scheduleAppointmentRouter from "../modules/scheduleAppointment/scheduleAppointment.routes.js";
import communityRouter from "../modules/community/community.route.js";
import communityGroupRouter from "../modules/community/communityGroup.route.js";
import communityAnnouncementRouter from "../modules/community/communityAnnouncement.route.js";
import directMessageRouter from "../modules/directMessage/directMessage.route.js";
import resourceRouter from "../modules/resource/resource.route.js";
import notificationRouter from "../modules/notification/notification.route.js";
import fcRouter from "../modules/functionalClassification/functionalClassification.route.js";
import metricsRouter from "../modules/metrics/metrics.route.js";
import chatRouter from "../modules/chat/chat.route.js";
import telehealthRouter from "../modules/telehealth/telehealth.route.js";
import gameRouter from "../modules/game/game.route.js";
import enrollmentRouter from "../modules/cpPatient/enrollment.route.js";
import outcomesRouter from "../modules/assessment/outcomes.route.js";
import adminRouter from "../modules/admin/admin.route.js";
import adherenceRouter from "../modules/assessment/adherence.route.js";
import reportRouter, { adminReportRouter } from "../modules/report/report.route.js";
import supportRouter, { adminSupportRouter } from "../modules/support/support.route.js";
import faqRouter, { adminFaqRouter } from "../modules/support/faq.route.js";
import rbacRouter, { rbacCheckRouter } from "../modules/admin/rbac.route.js";


router.use("/auth", authRouter);
router.use("/service-provider", serviceProviderRouter);
router.use("/caregiver", caregiverRouter);
router.use("/cp-patient", cpPatientRouter);
router.use("/assessment", assessmentRouter);
router.use("/user", userRouter);
router.use("/schedule-appointment", scheduleAppointmentRouter);
router.use("/community", communityRouter);
router.use("/community/:communityId/groups", communityGroupRouter);
router.use("/community/:communityId/announcements", communityAnnouncementRouter);
router.use("/direct-message", directMessageRouter);
router.use("/resource", resourceRouter);
router.use("/notification", notificationRouter);
router.use("/functional-classification", fcRouter);
router.use("/metrics", metricsRouter);
router.use("/chat", chatRouter);
router.use("/telehealth", telehealthRouter);
router.use("/game", gameRouter);
router.use("/enrollment", enrollmentRouter);
router.use("/outcomes", outcomesRouter);
router.use("/admin", adminRouter);
router.use("/adherence", adherenceRouter);
router.use("/report", reportRouter);
router.use("/admin/reports", adminReportRouter);
router.use("/support", supportRouter);
router.use("/admin/support", adminSupportRouter);
router.use("/faq", faqRouter);
router.use("/admin/faq", adminFaqRouter);
router.use("/admin/rbac", rbacRouter);
router.use("/rbac", rbacCheckRouter);


export default router;
