const GMFM_88_ITEM_TEXT = {
  A1: "SUP: Head in midline, turns head with extremities symmetrical",
  A2: "SUP: Brings hands to midline, fingers one with the other",
  A3: "SUP: Lifts head 45°",
  A4: "SUP: Flexes R hip and knee through full range",
  A5: "SUP: Flexes L hip and knee through full range",
  A6: "SUP: Reaches out with R arm, hand crosses midline toward toy",
  A7: "SUP: Reaches out with L arm, hand crosses midline toward toy",
  A8: "SUP: Rolls to PR over R side",
  A9: "SUP: Rolls to PR over L side",
  A10: "PR: Lifts head upright",
  A11: "PR on forearms: Lifts head upright, elbows extended, chest raised",
  A12: "PR on forearms: Weight on R forearm, fully extends opposite arm forward",
  A13: "PR on forearms: Weight on L forearm, fully extends opposite arm forward",
  A14: "PR: Rolls to SUP over R side",
  A15: "PR: Rolls to SUP over L side",
  A16: "PR: Pivots to R 90° using extremities",
  A17: "PR: Pivots to L 90° using extremities",
  B18: "SUP, hands grasped by examiner: Pulls self to sitting with head control",
  B19: "SUP: Rolls to R side, attains sitting",
  B20: "SUP: Rolls to L side, attains sitting",
  B21: "Sit on mat, supported at thorax by therapist: Lifts head upright, maintains 3 seconds",
  B22: "Sit on mat, supported at thorax by therapist: Lifts head midline, maintains 10 seconds",
  B23: "Sit on mat, arm(s) propping: Maintains, 5 seconds",
  B24: "Sit on mat: Maintains, arms free, 3 seconds",
  B25: "Sit on mat with small toy in front: Leans forward, touches toy, re-erects without arm propping",
  B26: "Sit on mat: Touches toy placed 45° behind child's R side, returns to start",
  B27: "Sit on mat: Touches toy placed 45° behind child's L side, returns to start",
  B28: "R side sit: Maintains, arms free, 5 seconds",
  B29: "L side sit: Maintains, arms free, 5 seconds",
  B30: "Sit on mat: Lowers to PR with control",
  B31: "Sit on mat with feet in front: Attains 4-point over R side",
  B32: "Sit on mat with feet in front: Attains 4-point over L side",
  B33: "Sit on mat: Pivots 90°, without arms assisting",
  B34: "Sit on bench: Maintains, arms and feet free, 10 seconds",
  B35: "STD: Attains sit on small bench",
  B36: "On the floor: Attains sit on small bench",
  B37: "On the floor: Attains sit on large bench",
  C38: "PR: Creeps forward 1.8m (6 ft)",
  C39: "4-point: Maintains, weight on hands and knees, 10 seconds",
  C40: "4-point: Attains sit, arms free",
  C41: "PR: Attains 4-point, weight on hands and knees",
  C42: "4-point: Reaches forward with R arm, hand above shoulder level",
  C43: "4-point: Reaches forward with L arm, hand above shoulder level",
  C44: "4-point: Crawls or hitches forward 1.8m (6 ft)",
  C45: "4-point: Crawls reciprocally forward 1.8m (6 ft)",
  C46: "4-point: Crawls up 4 steps on hands and knees/feet",
  C47: "4-point: Crawls backwards down 4 steps on hands and knees/feet",
  C48: "Sit on mat: Attains high kneel using arms, maintains, arms free, 10 seconds",
  C49: "High kneel: Attains half kneel on R knee using arms, maintains, arms free, 10 seconds",
  C50: "High kneel: Attains half kneel on L knee using arms, maintains, arms free, 10 seconds",
  C51: "High kneel: Knee walks forward 10 steps, arms free",
  D52: "On the floor: Pulls to stand at large bench",
  D53: "STD: Maintains, arms free, 3 seconds",
  D54: "STD: Holding on to large bench with one hand, lifts R foot, 3 seconds",
  D55: "STD: Holding on to large bench with one hand, lifts L foot, 3 seconds",
  D56: "STD: Maintains, arms free, 20 seconds",
  D57: "STD: Lifts L foot, arms free, 10 seconds",
  D58: "STD: Lifts R foot, arms free, 10 seconds",
  D59: "Sit on small bench: Attains stand without using arms",
  D60: "High kneel: Attains stand through half kneel on R knee, without using arms",
  D61: "High kneel: Attains stand through half kneel on L knee, without using arms",
  D62: "STD: Lowers to sit on floor with control, arms free",
  D63: "STD: Attains squat, arms free",
  D64: "STD: Picks up object from floor, arms free, returns to stand",
  E65: "STD, 2 hands on large bench: Cruises 5 steps to R",
  E66: "STD, 2 hands on large bench: Cruises 5 steps to L",
  E67: "STD, 2 hands held: Walks forward 10 steps",
  E68: "STD, 1 hand held: Walks forward 10 steps",
  E69: "STD: Walks forward 10 steps",
  E70: "STD: Walks forward 10 steps, stops, turns 180°, returns",
  E71: "STD: Walks backward 10 steps",
  E72: "STD: Walks forward 10 steps, carrying a large object with 2 hands",
  E73: "STD: Walks forward 10 consecutive steps between parallel lines 20cm (8 in) apart",
  E74: "STD: Walks forward 10 consecutive steps on a straight line 2cm (3/4 in) wide",
  E75: "STD: Steps over stick at knee level, R foot leading",
  E76: "STD: Steps over stick at knee level, L foot leading",
  E77: "STD: Runs 4.5m (15 ft), stops and returns",
  E78: "STD: Kicks ball with R foot",
  E79: "STD: Kicks ball with L foot",
  E80: "STD: Jumps 30cm (12 in) high, both feet simultaneously",
  E81: "STD: Jumps forward 30cm (12 in), both feet simultaneously",
  E82: "STD on R foot: Hops on R foot 10 times within a 60cm (24 in) circle",
  E83: "STD on L foot: Hops on L foot 10 times within a 60cm (24 in) circle",
  E84: "STD, holding 1 rail: Walks up 4 steps, holding 1 rail, alternating feet",
  E85: "STD, holding 1 rail: Walks down 4 steps, holding 1 rail, alternating feet",
  E86: "STD: Walks up 4 steps, alternating feet",
  E87: "STD: Walks down 4 steps, alternating feet",
  E88: "STD on 15cm (6 in) step: Jumps off, both feet simultaneously"
};

export const gmfm88Items = Object.entries(GMFM_88_ITEM_TEXT).map(([id, text]) => ({
  id,
  dimension: id[0],
  number: Number(id.slice(1)),
  text
}));

