export default {
    SUCCESS: 'SUCCESS',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    ALREADY_EXISTS: 'ALREADY_EXISTS',
    INVALID_USER: 'INVALID_USER',
    FAILED: 'FAILED',
    VERIFICATION_PENDING: 'VERIFICATION_PENDING',
    INVALID_TOKEN: 'INVALID_TOKEN',
    UNAUTHORIZED: 'UNAUTHORIZED',
    INVALID_CODE: 'INVALID_CODE',
    INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
    SOCIAL_LOGIN: 'SOCIAL_LOGIN',
    NO_FILES_FOUND: 'NO_FILES_FOUND',
    LOW_FUNDS: 'LOW_FUNDS'
}